apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /rest/catalogs
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /rest/catalogs
              port: 8080
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
